designpro/catalog/urls.py
from django.urls import path
from . import views
from .views import ApplicationListView, delete_application, ApplicationAllListView
urlpatterns = [
    path('', ApplicationAllListView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/profile/', ApplicationListView.as_view(), name='profile'),
    path('accounts/profile/createapp/', views.CreateAppView.as_view(), name='createapp'),
    path(r'delete_application/<pk>', delete_application, name='delete_application'),
]

designpro/designpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

designpro/catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils.crypto import get_random_string

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=200, verbose_name='Имя')
    surname = models.CharField(max_length=200, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=200, verbose_name='Отчество')
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True)
    email = models.EmailField(max_length=200, verbose_name='Почта', unique=True)
    password = models.CharField(max_length=200, verbose_name='Пароль')
    role = models.CharField(max_length=200, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')

    def __str__(self):
        return self.name

def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


class Application(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название', blank=False)
    username = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, verbose_name='Описание', help_text='Напишите описание ', blank=False)
    categories = models.ForeignKey('Categorise', verbose_name='Категория', on_delete=models.CASCADE)
    image = models.ImageField(max_length=254, verbose_name='Изображение', upload_to=get_name_file,
                              null=True, blank=False,
                              validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])])
    status = models.CharField(max_length=200, verbose_name='Статус',
                              choices=(('new', 'Новая'), ('in work', 'Принято в работу'), ('done', 'Выполнено')),
                              default='new')
    date = models.DateField(verbose_name='Дата добавления', auto_now_add=True)
    img = models.ImageField(max_length=254, verbose_name='Изображение', upload_to=get_name_file, null=True, blank=True,
                            validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])])
    comment = models.TextField(max_length=1000, verbose_name='Комментарий', help_text="Комментарий", blank=True)

    def __str__(self):
        return self.name


class Categorise(models.Model):
    name = models.CharField(max_length=200, help_text="Напишите категорию", blank=False)

    def __str__(self):
        return self.name

designpro/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
      {% block title %}<title>Design.pro</title>{% endblock %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <div class="container-fluid px-0">
            <header class="header">
                <section>
                    <h4 class="mr-md-auto p-2 text-white"><a  href="{% url 'index'  %}">DESIGN.PRO</a></h4>
                    <nav>
                        <li><a  href="{% url 'index'  %}">ГЛАВНАЯ</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{%url 'profile'%}">ЛИЧНЫЙ КАБИНЕТ</a></li>
                        <li><a href="{%url 'logout'%}">ВЫХОД</a></li>
                        {% else %}
                        <li><a href="{%url 'register'%}">РЕГИСТРАЦИЯ</a></li>
                        <li><a href="{%url 'login'%}">ВХОД</a>
                            {% endif %}
                    </nav>
                </section>
            </header>
            <div class="bg-white">
                <div class="container bg-white m-auto-0">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
             {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination justify-content-center m-auto">
                        <span class="page-links d-flex justify-content-center">
                            {% if page_obj.has_previous %}
                                <a class="pagination p" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                            {% endif %}
                            <span class="page-current p">
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a class="pagination p" href="{{ request.path }}?page={{ page_obj.next_page_number }}"> Следующая</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
        <footer class="footer_part d-flex justify-content-center align-items-center ">
                <p class="text-white-50">Выполнила: Чикулаева А.А.</p>
        </footer>
    </body>
</html>

designpro/templates/createapp.html
{% extends "base_generic.html" %}
{% block content %}
    <div class="bg-white ">
        <p class="zgl">Создание заявки</p>
        <div class="d-flex justify-content-center for-form">
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Создать"/>
            </form>
        </div>
    </div>
{% endblock %}

designpro/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
    <div>
        <P class="zgl">Выполненные планы помещений ({{count}})</P>
    </div>
    {% if application_list %}
        <ul>
        {% for application in application_list %}
            <div class=" box-shadow content-window">
                <div class="d-flex my-3 py-5 justify-content-center ">
                    <div class="image">
                        <img src="{{application.img.url}}">
                    </div>
                    <div class="card">
                        <div class="d-flex justify-content-start description flex-column">
                            <p class="pt-3 px-4 name"> {{application.name}}</p>
                            <p class="pt-1 px-4">Категория: {{application.categories}}</p>
                        </div>
                        <p class="p-4">{{application.description}}</p>
                        <div class="d-flex justify-content-start">
                            <p class="p-4 name">Комментарий дизайнера: </p>
                            <p class="py-4 px-1">{{application.comment}}</p>
                        </div>


                        <div class="d-flex justify-content-center" >
                            <p class="p-4"> {{application.date}}</p>
                                <p class="p-4"> - </p>
                                <p class="p-4 status"> {{application.status}} </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p class="zgl">Планов помещений нет</p>
    {% endif %}
{% endblock %}

designpro/templates/profile.html
{% extends "base_generic.html" %}
{% block content %}
    <p class="zgl">Ваши объявления</p>
    <div class="d-flex justify-content-center">
        <p class="sl"><a href="{% url 'profile' %}">Все</a></p>
        <p class="sl"><a href="{% url 'profile' %}?status=new"> Новые </a></p>
        <p class="sl"><a href="{% url 'profile' %}?status=in work"> В работе</a>  </p>
        <p class="sl"><a href="{% url 'profile' %}?status=done"> Выполненые </a></p>
    </div>
    <div class="d-flex justify-content-center content-window ">
        <p class="sl"><a href="{% url 'createapp' %}"> + Создать новое объявление</a></p>
    </div>
    {% if application_list %}
        <ul>
        {% for application in application_list %}
            <div class="box-shadow content-window">
                <div class="d-flex my-3 py-5 justify-content-center">
                    <div class="image">
                        <div class="img">
                            <p class="text">Изображение, загруженное пользователем:</p>
                            <img src="{{application.image.url}}">
                            {% if application.img %}
                                <p class="text">Изображение после редакции:</p>
                                <img src="{{application.img.url}}">
                            {% endif %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="d-flex justify-content-start description flex-column">
                            <p class="pt-3 px-4 name"> {{application.name}}</p>
                            <p class="pt-1 px-4">Категория: {{application.categories}}</p>
                        </div>
                        <p class="p-4">{{application.description}}</p>
                        {% if application.comment %}
                             <div class="d-flex justify-content-start">
                                <p class="p-4 name">Комментарий дизайнера: </p>
                                <p class="py-4 px-1">{{application.comment}}</p>
                            </div>
                        {% endif %}
                        <div class="d-flex justify-content-center" >
                            <p class="p-4"> {{application.date}}</p>
                                <p class="p-4"> - </p>
                                <p class="p-4 status"> {{application.status}} </p>
                                    {% if application.status == 'new' %}
                                        <p class="sl"><a href="#win1" >Удалить заказ</a></p>
                                        <a href="#x" class="overlay" id="win1"></a>
                                        <div class="popup">
                                            <p class="zgl">Вы действительно хотите удалить заказ?</p>
                                            <div class="d-flex justify-content-center" >
                                                <p class="sl"><a href="{% url 'delete_application' application.pk %}">Удалить заказ</a></p>
                                                <p class="sl close"><a href="{% url 'profile' %}">Нет</a></p>
                                            </div>
                                        </div>

                                    {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p class="zgl">Объявлений нет</p>
    {% endif %}
{% endblock %}